[0m22:03:40.996486 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210D50006E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210D2C85E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210D70A7D90>]}


============================== 22:03:41.004480 | 333c0ffe-80a1-4003-8b8e-c1acbcf4ed22 ==============================
[0m22:03:41.004480 [info ] [MainThread]: Running with dbt=1.10.6
[0m22:03:41.005228 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\admin\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m22:03:41.024112 [info ] [MainThread]: Creating dbt configuration folder at C:\Users\admin\.dbt
[0m22:03:53.893462 [debug] [MainThread]: Starter project path: C:\Users\admin\Accidents_in_France\.dbtenv\Lib\site-packages\dbt\include\starter_project
[0m22:03:53.929171 [info ] [MainThread]: 
Your new dbt project "dbt_accidents" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:03:53.930251 [info ] [MainThread]: Setting up your profile.
[0m22:05:01.826973 [info ] [MainThread]: Profile dbt_accidents written to C:\Users\admin\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m22:05:01.827950 [debug] [MainThread]: Command `dbt init` succeeded at 22:05:01.827837 after 80.98 seconds
[0m22:05:01.828264 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210D701FBB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210D7037AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210D5F85BF0>]}
[0m22:05:01.828598 [debug] [MainThread]: Flushing usage events
[0m22:05:03.410964 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:55:53.723684 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000155BA3DC6E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000155B8061E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000155BC47FD90>]}


============================== 23:55:53.732081 | 40e11ec8-5b30-46dc-9035-87ca89df89e0 ==============================
[0m23:55:53.732081 [info ] [MainThread]: Running with dbt=1.10.6
[0m23:55:53.736865 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\admin\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m23:55:53.737448 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\admin\Accidents_in_France\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:55:53.738412 [debug] [MainThread]: Command `dbt run` failed at 23:55:53.738273 after 0.21 seconds
[0m23:55:53.738806 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000155BC3F4050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000155BB36F770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000155BB368D10>]}
[0m23:55:53.739141 [debug] [MainThread]: Flushing usage events
[0m23:55:55.019821 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:56:13.982668 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245F17BC6E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245EF455E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245F3863D90>]}


============================== 23:56:13.990374 | 362419d0-1635-4a52-a427-f10923625657 ==============================
[0m23:56:13.990374 [info ] [MainThread]: Running with dbt=1.10.6
[0m23:56:13.991351 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\admin\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m23:56:14.011212 [info ] [MainThread]: dbt version: 1.10.6
[0m23:56:14.011799 [info ] [MainThread]: python version: 3.13.5
[0m23:56:14.012263 [info ] [MainThread]: python path: C:\Users\admin\Accidents_in_France\.dbtenv\Scripts\python.exe
[0m23:56:14.012736 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m23:56:14.079627 [info ] [MainThread]: Using profiles dir at C:\Users\admin\.dbt
[0m23:56:14.080241 [info ] [MainThread]: Using profiles.yml file at C:\Users\admin\.dbt\profiles.yml
[0m23:56:14.080659 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\admin\Accidents_in_France\dbt_project.yml
[0m23:56:14.082080 [info ] [MainThread]: adapter type: postgres
[0m23:56:14.082517 [info ] [MainThread]: adapter version: 1.9.0
[0m23:56:14.082870 [info ] [MainThread]: Configuration:
[0m23:56:14.083281 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m23:56:14.083772 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m23:56:14.084320 [info ] [MainThread]: Required dependencies:
[0m23:56:14.084725 [debug] [MainThread]: Executing "git --help"
[0m23:56:14.133796 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m23:56:14.134837 [debug] [MainThread]: STDERR: "b''"
[0m23:56:14.135409 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m23:56:14.136042 [info ] [MainThread]: Connection:
[0m23:56:14.136763 [info ] [MainThread]:   host: tri
[0m23:56:14.137154 [info ] [MainThread]:   port: 1
[0m23:56:14.137506 [info ] [MainThread]:   user: tri
[0m23:56:14.137834 [info ] [MainThread]:   database: accidents
[0m23:56:14.138164 [info ] [MainThread]:   schema: france
[0m23:56:14.138471 [info ] [MainThread]:   connect_timeout: 10
[0m23:56:14.138744 [info ] [MainThread]:   role: None
[0m23:56:14.139017 [info ] [MainThread]:   search_path: None
[0m23:56:14.139370 [info ] [MainThread]:   keepalives_idle: 0
[0m23:56:14.139730 [info ] [MainThread]:   sslmode: None
[0m23:56:14.140100 [info ] [MainThread]:   sslcert: None
[0m23:56:14.140472 [info ] [MainThread]:   sslkey: None
[0m23:56:14.140870 [info ] [MainThread]:   sslrootcert: None
[0m23:56:14.141368 [info ] [MainThread]:   application_name: dbt
[0m23:56:14.141970 [info ] [MainThread]:   retries: 1
[0m23:56:14.142901 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m23:56:14.327483 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m23:56:17.147071 [debug] [MainThread]: Using postgres connection "debug"
[0m23:56:17.147478 [debug] [MainThread]: On debug: select 1 as id
[0m23:56:17.147725 [debug] [MainThread]: Opening a new connection, currently in state init
[0m23:56:19.851171 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
could not translate host name "tri" to address: Name or service not known

[0m23:56:22.133931 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m23:56:22.134410 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m23:56:22.134696 [debug] [MainThread]: On debug: No close available on handle
[0m23:56:22.134958 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m23:56:22.135491 [info ] [MainThread]: [31m2 checks failed:[0m
[0m23:56:22.135900 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\admin\Accidents_in_France\dbt_project.yml> not found

[0m23:56:22.136520 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  could not translate host name "tri" to address: Name or service not known
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m23:56:22.137418 [debug] [MainThread]: Command `dbt debug` failed at 23:56:22.137302 after 8.34 seconds
[0m23:56:22.137713 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m23:56:22.137988 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245F3991CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245F39968D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245F3908D10>]}
[0m23:56:22.138313 [debug] [MainThread]: Flushing usage events
[0m23:56:23.636729 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:02:37.259872 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014FDF76CC20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014FE07EBED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014FE07EBB10>]}


============================== 00:02:37.267248 | ca00e5a6-361d-4a75-b2e6-ff3ea47bdf14 ==============================
[0m00:02:37.267248 [info ] [MainThread]: Running with dbt=1.10.6
[0m00:02:37.267857 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\admin\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt clean', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:02:37.268395 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\admin\Accidents_in_France\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:02:37.269500 [debug] [MainThread]: Command `dbt clean` failed at 00:02:37.269393 after 0.16 seconds
[0m00:02:37.269801 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014FE1918050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014FE079CEF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014FE18CD260>]}
[0m00:02:37.270092 [debug] [MainThread]: Flushing usage events
[0m00:02:38.680525 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:02:41.462058 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002515879CC20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025159817ED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025159817B10>]}


============================== 00:02:41.470169 | b7bf6761-8fff-4078-94ba-7ad009885843 ==============================
[0m00:02:41.470169 [info ] [MainThread]: Running with dbt=1.10.6
[0m00:02:41.471054 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\admin\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt deps', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:02:41.471837 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\admin\Accidents_in_France\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:02:41.473031 [debug] [MainThread]: Command `dbt deps` failed at 00:02:41.472884 after 0.17 seconds
[0m00:02:41.473389 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002515A948050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000251597D0EF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002515A8F9260>]}
[0m00:02:41.473693 [debug] [MainThread]: Flushing usage events
[0m00:02:42.704617 [debug] [MainThread]: An error was encountered while trying to flush usage events
